apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: acmetrader-config
spec:
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: acmetrader-config
    data:
      stockQuote.url: "http://www.ibm.com"
      tradeHistory.url: "http://www.ibm.com"
      portfolio.url: "http://www.ibm.com"
