apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: lab2-tradr-deploy
spec:
  template:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: lab2-tradr-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: lab2-tradr
      template:
        metadata:
          name: lab2-tradr
          labels:
            app: lab2-tradr
        spec:
          containers:
            - name: lab2-tradr
              image: __IMAGE__
              imagePullPolicy: Always
              env:
                - name: STOCK_QUOTE_URL
                  valueFrom:
                    configMapKeyRef:
                      name: lab2-tradr-config
                      key: stockQuote.url
                      optional: true
                - name: TRADE_HISTORY_URL
                  valueFrom:
                    configMapKeyRef:
                      name: lab2-tradr-config
                      key: tradeHistory.url
                - name: PORTFOLIO_URL
                  valueFrom:
                    configMapKeyRef:
                      name: lab2-tradr-config
                      key: portfolio.url
              livenessProbe:
                tcpSocket:
                  port: 3000
                initialDelaySeconds: 20
                periodSeconds: 60
