apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: labX-tradr-service
spec:
  template:
    apiVersion: v1
    kind: Service
    metadata:
      name: labX-tradr-service
    spec:
      selector:
        app: labX-tradr
      ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
