apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: labdt-tradr-service
spec:
  template:
    apiVersion: v1
    kind: Service
    metadata:
      name: labdt-tradr-service
    spec:
      selector:
        app: labdt-tradr
      ports:
        - nodePort: 32761
          port: 3000
      type: NodePort
